# See the full yml reference at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: rw-sls-4-web

# Uncomment org and app if you want to integrate your deployment with the Serverless dashboard. See https://www.serverless.com/framework/docs/dashboard/ for more details.
org: dac09
app: rw-sls-4

useDotenv: true
plugins:
  - serverless-lift

constructs:
  rw-web:
    type: static-website
    path: dist

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2 # This is the AWS region where the service will be deployed.
